### ISSUE TITLE
keys listing

### ISSUE THREAD

**Issue by ecava-dx** [flowdee/edd-software-license-manager#3]
Hi Flowdee,

Thanks for the plugin. Just to point out there's one issue when few items were purchased, only the last key get output to the email tag. So I suggest to change in emails.php:

$output = $license['item'] . ': ' . $license['key'];

to 

$output .= $license['item'] . ': ' . $license['key'];

**Comment by flowdee** [comment]
Ooops this issue wasn't highlighted to me sorry for the delay! Thanks i'll take a look into!
