### ISSUE TITLE
License Key Not Present In Receipt Or On The Check Out Display

### ISSUE THREAD

**Issue by btwatts** [flowdee/edd-software-license-manager#5]
The code is successfully creating a license key, but I don't see it in either the HTML or plain text receipts sent to the user.  Also, the key is not displayed to the user....

Unless the user can successfully retrieve the key (and much prefer automated), buying a licensed product doesn't work so much.

I haven't dug into the problem yet (because I need to get some sleep) and wondered if you are seeing the problem also.

**Comment by flowdee** [comment]
Hey @btwatts, thanks for reporting. You're running the lastest version of EDD & WP?

**Comment by btwatts** [comment]
Yes.  Everything is current.
I still haven't gotten to debugging....
...but I was thinking.

The price was set to zero for testing.

I'm sure the license key was created.

I wonder if 'free' is causing the problem.

Byron

**Comment by flowdee** [comment]
Can you check it with an other price than free?

**Comment by btwatts** [comment]
I did a test with Stripe in test mode and I do not see a license number either. 

The license was created as noted in the image.

I did an additional test with no template (text only) that is attached.

![secondlicense](https://cloud.githubusercontent.com/assets/7790134/12459265/7ab76aee-bf73-11e5-8024-ab4dd467dc8d.png)

[Gmail - New download purchase - Order #447.pdf](https://github.com/flowdee/edd-software-license-manager/files/97908/Gmail.-.New.download.purchase.-.Order.447.pdf)

[Gmail - Purchase Receipt.pdf](https://github.com/flowdee/edd-software-license-manager/files/97894/Gmail.-.Purchase.Receipt.pdf)
![licenseok](https://cloud.githubusercontent.com/assets/7790134/12459056/6330cf56-bf72-11e5-8570-f43c435b3201.png)

**Comment by btwatts** [comment]
I turned on debug (your extension checkbox) with another test of a free product.  This is what it says:

byronco@byron.com [~/www/wp-content/plugins/edd-software-license-manager/log]# cat edd_slm_debug.log
Log Date: Wed, 20 Jan 2016 20:15:07 +0000
--- License Key Creation - START ---
Item: Evergreen Webinar Sales System
- SLM Response Body: {"result":"success","message":"License successfully created","key":"569feacbb6077"}
- SLM Response code: 200
- SLM Response message: OK
  --- License Key Creation - END ---

An additional question:

How painful would it be to enable more parameters (like, how long is a license valid) to your extension?  I can look into it further if it would help.

**Comment by flowdee** [comment]
Thanks for your detailed reply! Can you give me a screenshot of the purchase email template out of the EDD settings page?

About the expiration date: I can think about, would be interesting as a new feature.

**Comment by btwatts** [comment]
I think this is what you're asking for:
![edd_payment](https://cloud.githubusercontent.com/assets/7790134/12475350/fc14dada-bfe7-11e5-98a2-de09afe26ff7.png)

**Comment by flowdee** [comment]
Yeah thanks.

In general you have to place the {slm_license_keys} placeholder into this template. Otherwise the license keys won't be shown within the receipt.

Right now displaying the keys on the checkout page is not yet implemented.

**Comment by btwatts** [comment]
I don't think I saw any documentation saying there are setup requirements.

Updating the template now.

Thanks!

**Comment by btwatts** [comment]
Yes that solves my problem.

Sorry for the confusion.

Thank you for your help!

**Comment by flowdee** [comment]
No problem :smile: 

Usually the placeholder stands below the receipt textarea field. I'll check it with the latest version, it might disappeared due to the latest EDD updates. Anyway I'm going to extend the documentation on wp.org.

As I wrote I'm going to show the license keys on the purchase detail page sooner or later. Just have to find some time to implement this. :+1:

**Comment by btwatts** [comment]
It's there properly.  I never thought to look there.

**Comment by btwatts** [comment]
...funny.  I just had this same problem on my test site and forgot to update my receipt ... again.
